name: Format HTML and CSS (Python)

on:
  push:
    paths:
      - '**.html'
      - '**.css'
  pull_request:
    paths:
      - '**.html'
      - '**.css'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install formatters
        run: |
          pip install htmlbeautifier cssbeautifier

      - name: Format HTML files
        run: |
          find . -name "*.html" -exec htmlbeautifier -r {} \;

      - name: Format CSS files
        run: |
          find . -name "*.css" -exec css-beautify -r {} \;

      - name: Show formatting changes
        run: git diff

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: format HTML and CSS files with Python formatters"
          branch: ${{ github.ref }}